int _ABVAR_1_dis;
int dtime = 200;
int ardublockUltrasonicSensorCodeAutoGeneratedReturnCM(int trigPin, int echoPin)
{
  int duration;
  pinMode(trigPin, OUTPUT);
  pinMode(echoPin, INPUT);
  digitalWrite(trigPin, LOW);
  delayMicroseconds(2);
  digitalWrite(trigPin, HIGH);
  delayMicroseconds(5);
  digitalWrite(trigPin, LOW);
  duration = pulseIn(echoPin, HIGH);
  duration = duration / 59;
  return duration;
}


void setup()
{
  Serial.begin(9600);
  _ABVAR_1_dis = 0;
  digitalWrite( 4 , LOW );
  pinMode(13, HIGH);
  pinMode(12, HIGH);
  pinMode(11, HIGH);
  pinMode(10, HIGH);
}

void loop()
{
  for (int i = 10; i <= 13; i++) {
    digitalWrite(i, HIGH);
  }
  _ABVAR_1_dis = ardublockUltrasonicSensorCodeAutoGeneratedReturnCM( 4 , 3 );
  dtime = map(_ABVAR_1_dis,0,100,50,500);
  delay(100);
  for (int i = 10; i <= 13; i++) {
    digitalWrite(i, LOW);
  }
  _ABVAR_1_dis = ardublockUltrasonicSensorCodeAutoGeneratedReturnCM( 4 , 3 );
  dtime = map(_ABVAR_1_dis,0,100,50,500);
  delay(dtime);
//  Serial.print(dtime);
//  Serial.println("");
}


