#include <LiquidCrystal.h>
#include <IRremote.h>
#include <Servo.h>
Servo myservo;
int pos = 0;
int dtime = 10;
const int TrigPin = 7; //发出超声波
const int EchoPin = 6; //收到反射回来的超声波
int RECV_PIN = 9;
IRrecv irrecv(RECV_PIN);
decode_results results;
LiquidCrystal lcd(3, 5, 10, 11, 12, 13);
int i = 0;
int _ABVAR_1_dis;
int ardublockUltrasonicSensorCodeAutoGeneratedReturnCM(int TrigPin, int EchoPin)
{
  int duration;
  pinMode(TrigPin, OUTPUT);
  pinMode(EchoPin, INPUT);
  digitalWrite(TrigPin, LOW);
  delayMicroseconds(2);
  digitalWrite(TrigPin, HIGH);
  delayMicroseconds(5);
  digitalWrite(TrigPin, LOW);
  duration = pulseIn(EchoPin, HIGH);
  duration = duration / 59;
  return duration;
}

void setup() {
  // put your setup code here, to run once:
  lcd.begin(16, 2);
//  lcd.print("12");
  Serial.begin(9600);
  irrecv.enableIRIn();
}

void loop() { 
  _ABVAR_1_dis = ardublockUltrasonicSensorCodeAutoGeneratedReturnCM( 7 , 6 );
  dtime = map(_ABVAR_1_dis,0,100,50,500);
  lcd.setCursor(0,0);
  lcd.print(dtime);
  lcd.setCursor(0, 2);
  lcd.print("cuixiaohan"); 
  delay(250);
  lcd.clear();
}
